"""remove classroom_id from courses table

Revision ID: 01257dc393e9
Revises: b9e0392a0904
Create Date: 2026-06-14 15:32:06.022047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01257dc393e9'
down_revision = 'b9e0392a0904'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_constraint('fk_courses_classroom_id', type_='foreignkey')
        batch_op.drop_column('classroom_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('classroom_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_courses_classroom_id', 'classrooms', ['classroom_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###
