"""add buildings table and update classrooms

Revision ID: 7d4039f94662
Revises: f3676bbdb23c
Create Date: 2026-06-14 15:18:47.598594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d4039f94662'
down_revision = 'f3676bbdb23c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buildings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('building_code', sa.String(length=20), nullable=False, comment='楼栋编号'),
    sa.Column('building_name', sa.String(length=50), nullable=False, comment='楼栋名称'),
    sa.Column('campus', sa.String(length=50), nullable=True, comment='校区'),
    sa.Column('description', sa.String(length=200), nullable=True, comment='备注'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('building_code')
    )
    with op.batch_alter_table('classrooms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('building_id', sa.Integer(), nullable=True, comment='楼栋ID'))
        batch_op.create_foreign_key('fk_classrooms_building_id', 'buildings', ['building_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_column('building')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classrooms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('building', sa.VARCHAR(length=50), nullable=False))
        batch_op.drop_constraint('fk_classrooms_building_id', type_='foreignkey')
        batch_op.drop_column('building_id')

    op.drop_table('buildings')
    # ### end Alembic commands ###
