"""add min_floor and max_floor to buildings

Revision ID: b9e0392a0904
Revises: 7d4039f94662
Create Date: 2026-06-14 15:23:10.645493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9e0392a0904'
down_revision = '7d4039f94662'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('buildings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('min_floor', sa.Integer(), nullable=True, comment='最低楼层'))
        batch_op.add_column(sa.Column('max_floor', sa.Integer(), nullable=True, comment='最高楼层'))

    with op.batch_alter_table('classrooms', schema=None) as batch_op:
        batch_op.alter_column('building_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classrooms', schema=None) as batch_op:
        batch_op.alter_column('building_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('buildings', schema=None) as batch_op:
        batch_op.drop_column('max_floor')
        batch_op.drop_column('min_floor')

    # ### end Alembic commands ###
