"""initial tables

Revision ID: d4ee514fe6e4
Revises: 
Create Date: 2026-05-30 17:29:15.554260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4ee514fe6e4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='用户ID'),
    sa.Column('username', sa.String(length=30), nullable=False, comment='登录账号'),
    sa.Column('password', sa.String(length=64), nullable=False, comment='密码(MD5加密)'),
    sa.Column('role', sa.Enum('admin', 'teacher', 'student'), nullable=False, comment='角色'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('students',
    sa.Column('student_id', sa.String(length=20), nullable=False, comment='学号'),
    sa.Column('name', sa.String(length=20), nullable=False, comment='姓名'),
    sa.Column('gender', sa.String(length=2), nullable=True, comment='性别'),
    sa.Column('major', sa.String(length=50), nullable=True, comment='专业'),
    sa.Column('class_name', sa.String(length=50), nullable=True, comment='班级'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='手机号'),
    sa.Column('email', sa.String(length=50), nullable=True, comment='邮箱'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='关联用户ID'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('student_id')
    )
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_students_user_id'), ['user_id'], unique=True)

    op.create_table('teachers',
    sa.Column('teacher_id', sa.String(length=20), nullable=False, comment='工号'),
    sa.Column('name', sa.String(length=20), nullable=False, comment='姓名'),
    sa.Column('gender', sa.String(length=2), nullable=True, comment='性别'),
    sa.Column('department', sa.String(length=50), nullable=True, comment='院系'),
    sa.Column('title', sa.String(length=30), nullable=True, comment='职称'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='手机号'),
    sa.Column('email', sa.String(length=50), nullable=True, comment='邮箱'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='关联用户ID'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('teacher_id')
    )
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teachers_user_id'), ['user_id'], unique=True)

    op.create_table('courses',
    sa.Column('course_id', sa.String(length=20), nullable=False, comment='课程编号'),
    sa.Column('course_name', sa.String(length=100), nullable=False, comment='课程名称'),
    sa.Column('credit', sa.Numeric(precision=3, scale=1), nullable=False, comment='学分'),
    sa.Column('hours', sa.Integer(), nullable=False, comment='学时'),
    sa.Column('teacher_id', sa.String(length=20), nullable=True, comment='授课教师工号'),
    sa.Column('semester', sa.String(length=30), nullable=True, comment='开课学期'),
    sa.Column('capacity', sa.Integer(), nullable=True, comment='容量'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.teacher_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('course_id')
    )
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_courses_teacher_id'), ['teacher_id'], unique=False)

    op.create_table('enrollments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.String(length=20), nullable=False, comment='学号'),
    sa.Column('course_id', sa.String(length=20), nullable=False, comment='课程编号'),
    sa.Column('enroll_time', sa.DateTime(), nullable=True, comment='选课时间'),
    sa.Column('status', sa.Integer(), nullable=True, comment='1正常 0退课'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'course_id', name='uk_student_course')
    )
    op.create_table('grades',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.String(length=20), nullable=False, comment='学号'),
    sa.Column('course_id', sa.String(length=20), nullable=False, comment='课程编号'),
    sa.Column('grade', sa.Numeric(precision=5, scale=1), nullable=True, comment='成绩'),
    sa.Column('remark', sa.String(length=100), nullable=True, comment='备注'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'course_id', name='uk_student_course_grade')
    )
    op.create_table('schedules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('course_id', sa.String(length=20), nullable=False, comment='课程编号'),
    sa.Column('day_of_week', sa.Integer(), nullable=True, comment='星期(1-7)'),
    sa.Column('start_time', sa.String(length=20), nullable=True, comment='开始节次/时间'),
    sa.Column('end_time', sa.String(length=20), nullable=True, comment='结束节次/时间'),
    sa.Column('classroom', sa.String(length=30), nullable=True, comment='教室'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schedules')
    op.drop_table('grades')
    op.drop_table('enrollments')
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_courses_teacher_id'))

    op.drop_table('courses')
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teachers_user_id'))

    op.drop_table('teachers')
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_students_user_id'))

    op.drop_table('students')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    # ### end Alembic commands ###
