"""add classroom_id to courses

Revision ID: f3676bbdb23c
Revises: b2c3d4e5f6a7
Create Date: 2026-06-14 15:13:13.620881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3676bbdb23c'
down_revision = 'b2c3d4e5f6a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('classroom_id', sa.Integer(), nullable=True, comment='绑定教室ID'))
        batch_op.create_foreign_key('fk_courses_classroom_id', 'classrooms', ['classroom_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_constraint('fk_courses_classroom_id', type_='foreignkey')
        batch_op.drop_column('classroom_id')

    # ### end Alembic commands ###
