from app.extensions import db
from app.models.user import User
from app.models.student import Student
from app.models.teacher import Teacher
from app.models.course import Course
from app.models.enrollment import Enrollment
from app.models.grade import Grade
from app.models.schedule import Schedule
from app.models.building import Building
from app.models.classroom import Classroom
from app.models.semester import Semester